### PR TITLE
Added spotless plugin.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
@fartem what do you think about this gradle plugin?

**Comment by fartem** [comment]
@javadev, I think this plugin is good. This repository don't have Code Style format.

**Comment by javadev** [comment]
Thak you for replying. This repository also doesn't have a license.

**Comment by fartem** [comment]
@javadev, why do I need to use Licence here? I'm not sure that it is full standalone app, it is repository with solutions.

**Comment by javadev** [comment]
I agree, for the standalone app license is not needed. I suggest to reuse codes in other projects will be easier in case license is present.

**Comment by fartem** [comment]
@javadev, yes. I think If I add a License, this will be some open License, and in all cases where this repository has and hasn't License it is still possible reuse a code.

**Comment by javadev** [comment]
> @javadev, yes. I think If I add a License, this will be some open License, and in all cases where this repository has and hasn't License it is still possible reuse a code.

I know projects where license is mandatory to use a library.

**Pull request closed without merging**
